const DATA={
  reviews:[
    {id:'rev_012',rating:2,date:'2026-06-18',product:'BlendGo Mini',text:'The blender works well, but the lid leaked inside my work bag on the second day. I now only use it at home.',theme:'Lid leakage',sentiment:'negative',verified:true},
    {id:'rev_044',rating:1,date:'2026-05-29',product:'MixMate Go',text:'The seal is unreliable. Even when tightened, smoothie drips from the cap during travel.',theme:'Lid leakage',sentiment:'negative',verified:true},
    {id:'rev_081',rating:5,date:'2026-07-02',product:'Our Product',text:'Compact enough for my desk and surprisingly easy to rinse after a protein shake.',theme:'Easy cleaning',sentiment:'positive',verified:true},
    {id:'rev_103',rating:3,date:'2026-04-11',product:'FreshSpin',text:'Good for soft fruit, but frozen strawberries sometimes stop the blades.',theme:'Frozen fruit performance',sentiment:'mixed',verified:false},
    {id:'rev_127',rating:4,date:'2026-07-19',product:'Our Product',text:'USB-C charging is convenient and one charge lasts through my weekday lunches.',theme:'Battery life',sentiment:'positive',verified:true}
  ],
  competitors:[
    {name:'BlendGo Mini',asin:'B0C7DEMO01',price:39.99,rating:4.3,reviews:8420,strength:'Brand visibility',weakness:'Leak complaints',coverage:78},
    {name:'MixMate Go',asin:'B0C7DEMO02',price:29.99,rating:4.1,reviews:3150,strength:'Low price',weakness:'Battery life',coverage:64},
    {name:'FreshSpin',asin:'B0C7DEMO03',price:44.99,rating:4.5,reviews:1870,strength:'Blade power',weakness:'Bulky design',coverage:81},
    {name:'Our Product',asin:'DRAFT',price:36.99,rating:null,reviews:0,strength:'USB-C + portability',weakness:'Unvalidated seal',coverage:68}
  ],
  pain:[
    {rank:1,id:'pain_001',name:'通勤携带时发生漏液',freq:'18 / 248',severity:'high',score:82,evidence:['rev_012','rev_044'],need:'可靠的防漏携带'},
    {rank:2,id:'pain_002',name:'无法稳定搅碎冷冻水果',freq:'15 / 248',severity:'high',score:76,evidence:['rev_103'],need:'更稳定的搅拌性能'},
    {rank:3,id:'pain_003',name:'电池续航低于预期',freq:'12 / 248',severity:'medium',score:63,evidence:['rev_127'],need:'可预测的多次使用续航'},
    {rank:4,id:'pain_004',name:'杯底和刀片区域难清洁',freq:'9 / 248',severity:'medium',score:54,evidence:['rev_081'],need:'快速无死角清洗'},
    {rank:5,id:'pain_005',name:'产品容量描述不够直观',freq:'7 / 248',severity:'medium',score:45,evidence:[],need:'购买前明确容量预期'}
  ],
  keywords:[
    {term:'portable blender',category:'核心',intent:'购买',relevance:98,source:'Autocomplete + 竞品',priority:'Primary'},
    {term:'personal smoothie maker',category:'长尾',intent:'购买',relevance:91,source:'竞品 Listing',priority:'Secondary'},
    {term:'travel blender cup',category:'场景',intent:'购买',relevance:88,source:'Review + Autocomplete',priority:'Secondary'},
    {term:'usb c rechargeable blender',category:'属性',intent:'比较',relevance:86,source:'产品事实',priority:'Secondary'},
    {term:'small blender for office',category:'场景',intent:'购买',relevance:81,source:'Review',priority:'Long-tail'},
    {term:'leakproof portable blender',category:'痛点',intent:'购买',relevance:79,source:'Review',priority:'Test only'}
  ]
};
const views={
overview:()=>`<div class="page-head"><div><span class="eyebrow">PROJECT OVERVIEW</span><h1>Amazon 运营总览</h1><p>从 248 条 Review、3 个直接竞品和当前 Listing 中提取可追溯的运营洞察。</p></div><div class="meta-line"><span>站点 <b>Amazon US</b></span><span>类目 <b>Portable Blenders</b></span><span>更新 <b>刚刚</b></span></div></div>
<div class="metric-grid"><div class="metric"><label>数据质量</label><strong>92</strong><small>+8 达标</small></div><div class="metric"><label>Review 样本</label><strong>248</strong><small>12 个月</small></div><div class="metric"><label>关键词覆盖</label><strong>68%</strong><small>+20% 空间</small></div><div class="metric"><label>待审核洞察</label><strong>7</strong><small>需要人工</small></div></div>
<div class="panel" style="margin-bottom:18px"><div class="panel-head"><div><h2>Agent 流水线</h2><p>分析已通过结构与证据校验</p></div><span class="tag">8 / 8 完成</span></div><div class="agent-flow">${['产品','竞品','Review','痛点','关键词','审计','生成','策略'].map((x,i)=>`<div class="agent-node"><div class="agent-icon">${i+1}</div><strong>${x} Agent</strong><small>已验证</small></div>${i<7?'<i class="flow-line"></i>':''}`).join('')}</div></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><div><h2>优先运营洞察</h2><p>按影响、证据强度与执行成本排序</p></div><button class="evidence-link" data-view-jump="strategy">查看策略 →</button></div><div class="panel-body insight-list">${DATA.pain.slice(0,4).map(p=>`<div class="insight"><span class="rank">0${p.rank}</span><div><h3>${p.name}</h3><p>${p.need} · 提及 ${p.freq}</p></div><span class="confidence ${p.rank>2?'medium':''}">${p.rank<3?'高':'中'}置信</span></div>`).join('')}</div></div>
<div class="panel"><div class="panel-head"><div><h2>Review 情感分布</h2><p>已区分星级与文本情感</p></div></div><div class="panel-body donut-wrap"><div class="donut"></div><div class="legend"><div><span><i style="background:#2f825f"></i>正面</span><b>50%</b></div><div><span><i style="background:#c86556"></i>负面</span><b>29%</b></div><div><span><i style="background:#e7b95d"></i>混合</span><b>14%</b></div><div><span><i style="background:#aeb8b2"></i>中性/不明</span><b>7%</b></div></div></div></div></div>
<div class="grid-equal"><div class="panel"><div class="panel-head"><h2>主要负面主题</h2><button class="evidence-link" data-view-jump="reviews">全部主题 →</button></div><div class="panel-body">${[['漏液',82],['冷冻水果性能',68],['电池续航',55],['清洁死角',41]].map(x=>`<div class="bar-row negative"><span>${x[0]}</span><div class="bar"><span style="width:${x[1]}%"></span></div><b>${x[1]}</b></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><h2>下一步行动</h2><button class="evidence-link" data-view-jump="strategy">全部行动 →</button></div><div class="panel-body action-list">${actionItems(3)}</div></div></div>`,
sources:()=>page('DATA CENTER','数据中心','导入并检查产品、竞品、Review 与关键词数据。',`<div class="panel"><div class="panel-body"><label class="upload-zone"><input type="file" id="csvInput" accept=".csv,.json"><strong>上传 Review CSV 或 JSON</strong><p>点击选择文件 · 数据只在当前浏览器内处理</p><span class="secondary-button">选择文件</span></label><div class="data-cards"><div class="data-card"><strong>product.json</strong><small>12 个字段 · 完整度 88%</small></div><div class="data-card"><strong>competitors.csv</strong><small>4 条记录 · 3 个有效 ASIN</small></div><div class="data-card"><strong>reviews.csv</strong><small id="reviewFileCount">248 条记录 · 已去重</small></div></div></div></div><div class="panel" style="margin-top:18px"><div class="panel-head"><h2>数据质量检查</h2><span class="tag">通过</span></div><div class="panel-body"><div class="bar-row"><span>字段完整度</span><div class="bar"><span style="width:94%"></span></div><b>94</b></div><div class="bar-row"><span>Review 去重率</span><div class="bar"><span style="width:98%"></span></div><b>98</b></div><div class="bar-row"><span>证据可追溯</span><div class="bar"><span style="width:100%"></span></div><b>100</b></div></div></div>`),
evidence:()=>page('EVIDENCE STORE','证据库','所有 AI 结论都能回到原始数据。',table(['证据 ID','来源','原文摘录','标签','操作'],DATA.reviews.map(r=>[`ev_${r.id}`,r.product,r.text.slice(0,72)+'…',r.theme,`<button class="evidence-link" data-evidence="${r.id}">查看原文</button>`]))),
product:()=>page('PRODUCT AGENT','产品分析','只使用卖家提供的事实建立 feature → benefit 链。',`<div class="metric-grid"><div class="metric"><label>明确特征</label><strong>8</strong></div><div class="metric"><label>核心功能</label><strong>4</strong></div><div class="metric"><label>使用场景</label><strong>5</strong></div><div class="metric"><label>缺失字段</label><strong>2</strong><small>需确认</small></div></div>${table(['产品特征','事实值','潜在利益','类型','证据'],[['杯体材料','BPA-free Tritan','轻量、便于携带','事实 → 推断','ev_product_01'],['充电接口','USB-C','办公室与旅行充电方便','事实 → 推断','ev_product_02'],['容量','380 ml','适合单人饮用','事实 → 推断','ev_product_03'],['刀片','6-blade stainless steel','潜在搅拌性能，仍需验证','未验证','ev_product_04']])}`),
competitors:()=>page('COMPETITOR AGENT','竞品分析','同站点、同用途和相近价格带的竞品快照。',`<div class="panel"><div class="panel-head"><h2>竞品表现矩阵</h2><span class="tag">采集于 2026-08-12</span></div>${table(['产品','价格','Rating','Reviews','主要优势','主要弱点','关键词覆盖'],DATA.competitors.map(c=>[c.name,'$'+c.price,c.rating??'—',c.reviews.toLocaleString(),c.strength,c.weakness,`<span class="score">${c.coverage}%</span>`]))}</div><div class="grid-equal" style="margin-top:18px"><div class="panel"><div class="panel-head"><h2>差异化机会</h2></div><div class="panel-body insight-list"><div class="insight"><span class="rank">01</span><div><h3>防漏便携定位</h3><p>2 个竞品存在漏液 Review，但发布前必须通过产品测试。</p></div><span class="confidence">高证据</span></div><div class="insight"><span class="rank">02</span><div><h3>办公室单人使用场景</h3><p>Review 客户语言明确，竞品 Listing 覆盖较弱。</p></div><span class="confidence medium">中置信</span></div></div></div><div class="panel"><div class="panel-head"><h2>数据限制</h2></div><div class="panel-body"><p style="font-size:11px;line-height:1.8;color:var(--muted)">价格为时间点快照；Review 为可见样本；未估计销量、市场份额或 PPC 花费。页面未展示的功能不能直接判定为产品缺失。</p></div></div></div>`),
reviews:()=>page('REVIEW AGENT','Review 分析','方面级情感、主题频率、使用场景与原文证据。',`<div class="grid-2"><div class="panel"><div class="panel-head"><h2>主题优先级</h2><span class="tag">样本 248</span></div><div class="panel-body">${[['漏液',82],['冷冻水果性能',68],['续航',55],['易清洁',74],['便携尺寸',70]].map((x,i)=>`<div class="bar-row ${i<3?'negative':''}"><span>${x[0]}</span><div class="bar"><span style="width:${x[1]}%"></span></div><b>${x[1]}</b></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><h2>分析控制</h2></div><div class="panel-body"><p style="font-size:10px;color:var(--muted);line-height:1.8">✓ 星级与文本情感分开<br>✓ 同一 Review 对同主题只计一次<br>✓ 代表引文可回查<br>✓ 保留 mixed / unclear<br>✓ 展示样本分母与偏差</p></div></div></div>${table(['Review','星级','方面','情感','原文证据'],DATA.reviews.map(r=>[r.id,r.rating+' ★',r.theme,r.sentiment,`<button class="evidence-link" data-evidence="${r.id}">查看</button>`]))}`),
pain:()=>page('PAIN POINT AGENT','用户痛点','将 Review 主题转为有频率、严重度和商业影响的机会。',`<div class="panel"><div class="panel-head"><h2>痛点优先级</h2><span class="tag">公式化评分</span></div>${table(['优先级','痛点','频率','严重度','需求','评分','证据'],DATA.pain.map(p=>['#'+p.rank,p.name,p.freq,`<span class="severity ${p.severity}">${p.severity}</span>`,p.need,`<span class="score">${p.score}</span>`,p.evidence.length?`<button class="evidence-link" data-evidence="${p.evidence[0]}">${p.evidence.length} 条证据</button>`:'待补充']))}</div>`),
keywords:()=>page('KEYWORD AGENT','关键词研究','按来源、相关性、意图和使用位置分层，不虚构搜索量。',`<div class="panel"><div class="panel-head"><h2>关键词池</h2><span class="tag">6 个已批准</span></div>${table(['关键词','分类','意图','相关性','来源','建议位置'],DATA.keywords.map(k=>[k.term,k.category,k.intent,`<span class="score">${k.relevance}</span>`,k.source,k.priority]))}</div><div class="panel" style="margin-top:18px"><div class="panel-head"><h2>关键词分组</h2></div><div class="panel-body keyword-cloud">${DATA.keywords.map((k,i)=>`<span class="keyword ${i>1?'secondary':''} ${i>3?'long':''}">${k.term}</span>`).join('')}</div></div><div class="panel" style="margin-top:18px"><div class="panel-body"><p style="font-size:10px;color:var(--muted);margin:0"><b>数据边界：</b>Autocomplete 只作为需求信号。当前未接入授权搜索量数据，因此 monthly_search_volume 保持 null。</p></div></div>`),
listing:()=>page('LISTING WORKSPACE','Listing 工作台','人工批准事实与关键词后，生成可审查的 Listing 草稿。',`<div class="metric-grid"><div class="metric"><label>审计得分</label><strong>72</strong></div><div class="metric"><label>关键词覆盖</label><strong>88%</strong><small>草稿</small></div><div class="metric"><label>事实支持率</label><strong>100%</strong></div><div class="metric"><label>阻止声明</label><strong>2</strong><small>已移除</small></div></div><div class="panel"><div class="tabs"><button class="tab active">优化草稿</button><button class="tab">原 Listing</button><button class="tab">审计问题</button></div><div class="panel-body listing-editor"><div class="field-block full"><label>AMAZON TITLE <span id="titleCount">0 / 200</span></label><textarea id="titleField">Portable Blender, 380ml Personal Smoothie Maker with USB-C Rechargeable Base, BPA-Free Travel Blender Cup for Office and Daily Use</textarea></div>${[1,2,3,4,5].map((n,i)=>`<div class="field-block ${n===5?'full':''}"><label>BULLET ${n}<span>已验证</span></label><textarea>${['BLEND ON YOUR SCHEDULE — Prepare personal smoothies at your desk, at home, or while traveling with a compact 380ml design.','USB-C RECHARGEABLE — Charge with a compatible USB-C cable for convenient everyday use in the office or kitchen.','BPA-FREE TRITAN CUP — Lightweight cup material supports easy carrying and everyday drink preparation.','SIMPLE DAILY CLEANUP — Rinse the cup promptly after use; detachable components help make routine cleaning easier.','MADE FOR ONE — Personal capacity helps reduce oversized batches and fits naturally into individual routines.'][i]}</textarea></div>`).join('')}<div class="field-block full"><label>BACKEND SEARCH TERMS <span>无品牌词</span></label><textarea>personal smoothie maker travel blender cup small blender for office rechargeable mini blender</textarea></div></div></div><div class="panel" style="margin-top:18px"><div class="panel-head"><h2>人工审核 Gate</h2><span class="tag" id="approvalStatus">等待批准</span></div><div class="panel-body"><div class="action-item"><input type="checkbox" class="approval-check"><div><h3>产品事实已核对</h3><p>容量、材料、接口与包装内容和实物一致。</p></div></div><div class="action-item"><input type="checkbox" class="approval-check"><div><h3>合规声明已核对</h3><p>未使用无证据的性能、健康、安全或比较级声明。</p></div></div><div class="action-item"><input type="checkbox" class="approval-check"><div><h3>关键词与品牌风险已核对</h3><p>未使用竞品商标词或与产品无关关键词。</p></div></div><button class="primary-button" id="approveListing" style="margin-top:12px">批准 Listing 草稿</button></div></div>`),
strategy:()=>page('STRATEGY AGENT','运营策略','把已验证洞察转成有负责人、指标和风险的行动清单。',`<div class="metric-grid"><div class="metric"><label>Now</label><strong>3</strong></div><div class="metric"><label>Next</label><strong>4</strong></div><div class="metric"><label>Later</label><strong>2</strong></div><div class="metric"><label>需人工决策</label><strong>3</strong></div></div><div class="panel"><div class="panel-head"><h2>行动路线图</h2><span class="tag">Impact × Confidence × Effort</span></div><div class="panel-body action-list">${actionItems(6)}</div></div>`),
report:()=>page('FINAL REPORT','最终报告','汇总证据、洞察、Listing 建议与下一步行动。',`<div class="panel"><div class="panel-head"><div><h2>Amazon AI 运营分析报告</h2><p>Portable Blender · Amazon US · 2026-08-12</p></div><button class="primary-button" id="downloadJson">下载 JSON</button></div><div class="panel-body"><h3 style="font-size:13px">执行摘要</h3><p style="font-size:11px;line-height:1.8;color:var(--muted)">产品在 USB-C 充电、单人容量和办公室场景上具有清晰表达空间。竞品 Review 中最强的可行动信号是携带漏液与冷冻水果搅拌稳定性，但前者必须先完成实物防漏测试，才能进入 Listing 声明。</p><h3 style="font-size:13px;margin-top:24px">已验证结论</h3>${table(['结论','证据强度','建议'],[['办公室单人使用场景明确','高','在 Bullet 1 强化场景'],['USB-C 是有效差异属性','高','Title + Bullet 2'],['防漏是高优先级需求','高','先产品测试，后文案声明'],['搜索量与销量数据缺失','明确限制','接入授权数据前保持 null']])}<h3 style="font-size:13px;margin-top:24px">优先行动</h3><div class="action-list">${actionItems(4)}</div></div></div>`)
};
function page(eyebrow,title,desc,body){return `<div class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${desc}</p></div><div class="meta-line"><span>Schema <b>v1.0</b></span><span>Evidence <b>100%</b></span></div></div>${body}`}
function table(headers,rows){return `<div class="panel"><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
function actionItems(n){const a=[['验证杯盖防漏性能','产品','高','进行 50 次倒置与通勤振动测试；通过前不使用 leakproof 声明。'],['修订 Title 关键词顺序','Listing','高','将核心词前置，同时保留自然可读性。'],['建立办公室场景广告测试','广告','中','小预算测试 3 个场景长尾词，不预测 ROAS。'],['补充容量对比信息图','内容','中','用常见物体参照，减少容量预期偏差。'],['监测冷冻水果主题','产品','中','按月跟踪负面主题率和退货原因。'],['接入授权关键词数据','数据','低','补充搜索量、竞争度与广告账户表现。']];return a.slice(0,n).map((x,i)=>`<label class="action-item"><input type="checkbox"><div><h3>${x[0]}</h3><p>${x[3]} · Owner: ${x[1]}</p></div><span class="priority">${x[2]}优先</span></label>`).join('')}
const app=document.getElementById('appView');const labels={overview:'运营总览',sources:'数据中心',evidence:'证据库',product:'产品分析',competitors:'竞品分析',reviews:'Review 分析',pain:'用户痛点',keywords:'关键词研究',listing:'Listing 工作台',strategy:'运营策略',report:'最终报告'};
function render(view='overview'){app.innerHTML=views[view]();document.getElementById('pageCrumb').textContent=labels[view];document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));wireView(view);window.scrollTo(0,0)}
function wireView(view){document.querySelectorAll('[data-view-jump]').forEach(x=>x.onclick=()=>render(x.dataset.viewJump));document.querySelectorAll('[data-evidence]').forEach(x=>x.onclick=()=>openEvidence(x.dataset.evidence));if(view==='sources'){document.getElementById('csvInput').onchange=handleFile}if(view==='listing'){const f=document.getElementById('titleField');const c=()=>document.getElementById('titleCount').textContent=`${f.value.length} / 200`;f.oninput=c;c();document.getElementById('approveListing').onclick=approveListing}if(view==='report')document.getElementById('downloadJson').onclick=downloadReport}
document.querySelectorAll('.nav-item').forEach(x=>x.onclick=()=>{render(x.dataset.view);document.getElementById('sidebar').classList.remove('open')});document.getElementById('mobileMenu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
function openEvidence(id){const r=DATA.reviews.find(x=>x.id===id)||DATA.reviews[0];document.getElementById('dialogTitle').textContent=`${r.theme} · ${r.id}`;document.getElementById('dialogContent').innerHTML=`<div class="quote">“${r.text}”</div><div class="evidence-meta"><div><label>星级</label><strong>${r.rating} / 5</strong></div><div><label>日期</label><strong>${r.date}</strong></div><div><label>Verified</label><strong>${r.verified?'Yes':'Unknown'}</strong></div></div><p style="font-size:9px;color:var(--muted);margin-top:15px">来源：${r.product} · inference_type: fact · 该原文仅用于支持当前主题，不代表全部买家。</p>`;document.getElementById('evidenceDialog').showModal()}
document.getElementById('closeDialog').onclick=()=>document.getElementById('evidenceDialog').close();
function handleFile(e){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).split(/\r?\n/).filter(Boolean).length-1;document.getElementById('reviewFileCount').textContent=`${Math.max(lines,0)} 条记录 · 等待字段映射`;document.getElementById('sourceCount').textContent=Math.max(lines,0);toast(`已读取 ${f.name}，未上传到服务器`)};reader.readAsText(f)}
function approveListing(){const checks=[...document.querySelectorAll('.approval-check')];if(!checks.every(x=>x.checked)){toast('请先完成全部人工审核项');return}document.getElementById('approvalStatus').textContent='已批准';document.getElementById('approvalStatus').style.color='var(--green)';toast('Listing 草稿已通过人工 Gate')}
function downloadReport(){const payload={schema_version:'1.0.0',project:'Portable Blender',marketplace:'US',data_quality:92,competitors:DATA.competitors,pain_points:DATA.pain,keywords:DATA.keywords,quality_control:{unsupported_claims:[],human_review_required:true}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='amazon-operations-report.json';a.click();URL.revokeObjectURL(a.href);toast('JSON 报告已导出')}
document.getElementById('exportButton').onclick=()=>render('report');document.getElementById('runButton').onclick=()=>{document.getElementById('pipelineList').innerHTML=['数据校验','产品分析','竞品分析','Review 分析','痛点提取','关键词研究','Listing 审计','运营策略'].map((x,i)=>`<div class="pipeline-step"><i>${i+1}</i><span>${x}</span></div>`).join('');document.getElementById('runDialog').showModal()};document.querySelectorAll('[data-close-run]').forEach(x=>x.onclick=()=>document.getElementById('runDialog').close());document.getElementById('startPipeline').onclick=async()=>{const steps=[...document.querySelectorAll('.pipeline-step')];document.getElementById('startPipeline').disabled=true;for(const s of steps){s.classList.add('running');s.querySelector('i').textContent='…';await new Promise(r=>setTimeout(r,330));s.classList.remove('running');s.classList.add('done');s.querySelector('i').textContent='✓'}document.getElementById('startPipeline').disabled=false;toast('8 个分析任务已完成并通过校验');setTimeout(()=>document.getElementById('runDialog').close(),500)};
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2600)}
render();
